### ISSUE TITLE
Can't load 1.6.2 but 1.5 loads without issues

### ISSUE THREAD

**Issue by cprn** [IldarW/WurmBot#60]
I updated from 1.5 to 1.6.2 and this happened:
```java
java.io.FileNotFoundException: e:/home/shared/Steam/steamapps/common/Wurm Unlimited/WurmLauncher/mods/WurmBot/WurmBot.jar (No such file or directory)
```
Basic commands like `look` or `getid` work fine, but `bot` commands don't load, only `bot pause` and `bot off` are available.

I confirmed it works fine with version 1.5 but versions 1.6, 1.6.1 and 1.6.2 all behave as mentioned above.
I thought it might have to do with library location so I moved the game back to default library - it didn't help - 1.5 still works fine, 1.6+ don't. Other mods work fine when I try them with my private server so it's not a loader issue, I think. For the time being I'm staying with downgraded version.

Please, advice.

**Comment by IldarW** [comment]
fixed e449c62576ad8976cc3c1c6481c2f65670abcf24

**Comment by cprn** [comment]
Still not the right path. It's missing leading slash `/` now:
```java
java.io.FileNotFoundException: home/shared/Steam/steamapps/common/Wurm Unlimited/WurmLauncher/mods/WurmBot/WurmBot.jar (No such file or directory)
```
The correct absolute path in this case is this (with the leading root directory `/`):
```java
/home/shared/Steam/steamapps/common/Wurm Unlimited/WurmLauncher/mods/WurmBot/WurmBot.jar
```
